### ISSUE TITLE
Thinking about making this ready for VS 2015?

### ISSUE THREAD

**Issue by InDieTasten** [telerik/kendo-ui-demos-service#1]
Concurrently this repo is not clone-and-run capable, because packages, project files and dependencies are out of date and wont work properly with VS2015. Maybe add this as an extra public branch?

**Comment by limsteven** [comment]
I'm having the same problem in getting it to work in VS2015

**Comment by tsvetomir** [comment]
This project is only meant to serve as a reference, not as a generic sample.
We don't plan to update the project to VS2015 for the moment.

**Comment by InDieTasten** [comment]
Is there no chance of keeping this open, just in case a community member is interested in doing it for you? I do not have resources for that, But maybe someone else does? Or do you not accept changes by the community for this repo?

**Comment by tsvetomir** [comment]
We're happy to accept a PR for upgrading the project to VS2015. I'll keep the issue closed as "won't fix".

**Comment by InDieTasten** [comment]
The label is missing though
